# Generated by Django 3.1.7 on 2021-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
